package com.dilaraceylan.soccergame.entities.concrete;

import lombok.Getter;
import lombok.Setter;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import org.hibernate.annotations.GenericGenerator;

/**
 * TransferList generated by hbm2java
 */
@Entity
@Table(name = "transfer_list", uniqueConstraints = @UniqueConstraint(columnNames = "player_id"))
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class TransferList {

    @Id
    @GeneratedValue(generator = "native")
    @GenericGenerator(name = "native", strategy = "native")
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "player_id", unique = true, nullable = false, insertable = false, updatable = false)
    private Player player;

    @Column(name = "player_id")
    private Long playerId;
    
    @NotBlank
    @Size(max = 50, message = "Price can contain up to the 50 characters")
    @Column(name = "price", nullable = false, length = 50)
    private String price;

    public TransferList(Long playerId, String price) {
        this.playerId = playerId;
        this.price = price;
    }
}
